In [6]:
from PIL import Image
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import mnist

In [7]:
x_train = mnist.train_images()
y_train = mnist.train_labels()

In [8]:
x_test = mnist.test_images()
y_test = mnist.test_labels()

In [9]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

In [10]:
x_train = x_train.reshape((-1, 28*28))

In [11]:
x_test = x_test.reshape((-1, 28*28))

In [12]:
x_train.shape, x_test.shape

((60000, 784), (10000, 784))

In [13]:
x_train = (x_train/256)
x_test = (x_test/256)

In [14]:
clf = MLPClassifier(solver='adam', activation='relu', hidden_layer_sizes=(64,64))

In [15]:
clf.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(64, 64))

In [16]:
predictions = clf.predict(x_test)

In [17]:
acc = confusion_matrix(y_test, predictions)

In [18]:
print(acc)

[[ 967    0    0    0    2    0    3    2    5    1]
 [   0 1124    3    2    0    1    1    1    3    0]
 [   3    1 1007    4    2    0    1    5    9    0]
 [   0    0    4  984    1    7    0    4    1    9]
 [   2    2    4    0  960    0    3    1    1    9]
 [   3    0    0    6    0  867    5    0    5    6]
 [   4    2    3    1    6    5  934    0    3    0]
 [   0    3   11    5    0    0    0  999    3    7]
 [   5    2    4    5    4    4    1    4  942    3]
 [   2    2    0    4    9    3    0    5    3  981]]


In [21]:
def accuracy(matrix):
    diagonal = matrix.trace()
    elements = matrix.sum()
    return diagonal/elements

In [22]:
print(accuracy(acc))

0.9765


In [23]:
predictions

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [24]:
predictions.shape

(10000,)