In [63]:
from sklearn import datasets
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.preprocessing import LabelEncoder

In [64]:
data = pd.read_csv('car.data')

In [65]:
data.head()


vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [66]:
data.columns = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [67]:
data.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [68]:
X = data[['buying', 'maint', 'safety']].values

In [69]:
y=data[['class']]

In [70]:
print(X,y)

[['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ['vhigh' 'vhigh' 'low']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1722   good
1723  vgood
1724  unacc
1725   good
1726  vgood

[1727 rows x 1 columns]


In [71]:
#Converting the data
Le  = LabelEncoder()
for i in range(len(X[0])):
    X[:,i] = Le.fit_transform(X[:,i])

In [72]:
print(X)

[[3 3 2]
 [3 3 0]
 [3 3 1]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [73]:
#Convert v2
label_mapping = {
    'unacc': 0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class'] = y['class'].map(label_mapping)
y=np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


C:\Users\orkun\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [76]:
#model

knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)
knn.fit(X_train, y_train)

pred = knn.predict(X_test)

acc = metrics.accuracy_score(y_test, pred)
print(pred)
print(acc)

[0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 3 3 3 0 0 1 0 0 0 1 0 2 0 1 0 0 0 2 3 0 0 0
 0 1 0 0 0 0 0 0 1 0 1 0 0 3 0 0 0 0 2 1 0 0 0 1 1 0 0 2 1 0 1 0 0 0 0 0 0
 0 0 1 3 1 0 0 0 0 2 0 2 1 0 1 1 1 0 3 0 0 0 0 0 0 3 0 0 0 0 0 0 1 0 0 1 0
 1 3 0 0 0 1 0 0 0 0 0 0 1 1 0 0 3 0 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 3 0
 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 3 1 0 0 1 0 3 0 3 3 1 3 0 0 0 0 1 1 0 0 1
 0 0 1 0 0 1 0 1 1 0 0 0 0 3 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1
 0 2 0 0 0 1 1 0 0 1 1 0 0 0 3 0 1 0 0 0 0 0 0 0 0 0 3 1 0 0 0 0 0 1 0 0 0
 0 1 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1
 1 1 1 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 1 1 0 0 1 0 1 3 0 0 1 0 0 1 0 0
 0 0 0 0 0 1 0 1 0 1 1 0 0]
0.7601156069364162


C:\Users\orkun\anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """
